id            = "conf-alloy"
name          = "conf.alloy"
version       = "0.0.1"
schema_version = 1
authors       = ["Gabriel Saudade <gabri.saudade@gmail.com>", "Matt Conway"]
description   = "Syntax highlighting and language basics for conf.alloy"

[grammars.alloy]
repository = "https://github.com/mattsre/tree-sitter-alloy"
rev        = "3e18eb4e97f06c57a3925f3d20bef6329a6eaef3"

[language_servers.alloy-hover]
name      = "Alloy Hover"
languages = ["conf.alloy"]
