[package]
name = "alloy-hover-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
tower-lsp = "0.20"
tokio = { version = "1", features = ["rt-multi-thread", "macros","io-std"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
anyhow = "1.0"
